// -*- mode: c++ -*-

/******		THIS FILE IS AUTOGENERATED, DO NOT EDIT !!	******/


#include <string>
using std::string; 

#include <version-info/GVersion.h>

const string GVersion::fGitBranch = "master";
const string GVersion::fGitTag = "v0.0.0-12-g84c9caa";
const string GVersion::fCompileFlags = "c++ -std=c++17 -fPIC -std=c++17 -ggdb -g -o xml-unit-tests xml-dll-test.o TestGXmlClassFactory.o TestGXmlValidatorImpl.o GVersion.o -L /home/perthi/github/logmaster/build/x86/lib -lm -ltestlib -lutilities -lcmdline -llogmaster -lreadline -lgtest -lpthread -lX11 -llogmaster -lutilities -lcmdline -lreadline -lxml-embc -lxml2";
const string GVersion::fLinkFlags = "-L /home/perthi/github/logmaster/build/x86/lib -lm -ltestlib -lutilities -lcmdline -llogmaster -lreadline -lgtest -lpthread -lX11 -llogmaster -lutilities -lcmdline -lreadline -lxml-embc -lxml2";
string GVersion::fOriginalExeName = "unknowne_exefile";
const string GVersion::fGitInfo = "__ Remote URLs:\n\
origin	git_github.com:perthi/logmaster.git (fetch)\n\
origin	git_github.com:perthi/logmaster.git (push)\n\
__ Remote Branches:\n\
  origin/HEAD -> origin/master\n\
  origin/master\n\
__ Local Branches:\n\
_ master\n\
__ Most Recent Commit:\n\
commit 84c9caa14b1777b854e943f39abbf19dcc7c6995\n\
Author: perthi <pth_embc.no>\n\
    adding docygen config\n\
Type 'git log' for more commits, or 'git show <commit id>' for full commit details.\n\
__ Configuration (.git/config):\n\
user.email=pth_embc.no\n\
user.name=perthi\n\
push.default=matching\n\
core.repositoryformatversion=0\n\
core.filemode=true\n\
core.bare=false\n\
core.logallrefupdates=true\n\
remote.origin.url=git_github.com:perthi/logmaster.git\n\
remote.origin.fetch=+refs/heads/_:refs/remotes/origin/_\n\
branch.master.remote=origin\n\
branch.master.merge=refs/heads/master\n\
";


